"""Add platform-agnostic agent models and adapters

Revision ID: 496c92a03b4e
Revises: 002_settlement
Create Date: 2025-11-21 17:32:35.740637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '496c92a03b4e'
down_revision: Union[str, None] = '002_settlement'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_executions',
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('ledger_event_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_agent_executions_agent_id_agents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_executions'))
    )
    op.create_index('ix_agent_executions_agent', 'agent_executions', ['agent_id'], unique=False)
    op.create_index('ix_agent_executions_created', 'agent_executions', ['created_at'], unique=False)
    op.create_index('ix_agent_executions_status', 'agent_executions', ['status'], unique=False)
    op.create_index('ix_agent_executions_user', 'agent_executions', ['user_id'], unique=False)
    op.create_table('agent_reputations',
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('total_executions', sa.Integer(), nullable=False),
    sa.Column('successful_executions', sa.Integer(), nullable=False),
    sa.Column('failed_executions', sa.Integer(), nullable=False),
    sa.Column('success_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('avg_latency_ms', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('p50_latency_ms', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('p95_latency_ms', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('p99_latency_ms', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('avg_cost', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('trust_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('last_execution_at', sa.DateTime(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_agent_reputations_agent_id_agents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_reputations')),
    sa.UniqueConstraint('agent_id', name=op.f('uq_agent_reputations_agent_id'))
    )
    op.create_index('ix_agent_reputations_agent', 'agent_reputations', ['agent_id'], unique=False)
    op.create_index('ix_agent_reputations_success_rate', 'agent_reputations', ['success_rate'], unique=False)
    op.create_index('ix_agent_reputations_trust_score', 'agent_reputations', ['trust_score'], unique=False)
    # Add new columns (nullable for SQLite compatibility with existing data)
    op.add_column('agents', sa.Column('platform', sa.String(length=50), nullable=True, server_default='claude'))
    op.add_column('agents', sa.Column('endpoint_url', sa.Text(), nullable=True))
    op.add_column('agents', sa.Column('agent_metadata', sa.JSON(), nullable=True, server_default='{}'))
    op.add_column('agents', sa.Column('owner_id', sa.String(length=36), nullable=True))
    op.create_index('ix_agents_platform', 'agents', ['platform'], unique=False)
    op.add_column('audit_trails', sa.Column('workflow_metadata', sa.JSON(), nullable=False))
    op.drop_column('audit_trails', 'metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_trails', sa.Column('metadata', sqlite.JSON(), server_default=sa.text("'{}'"), nullable=False))
    op.drop_column('audit_trails', 'workflow_metadata')
    op.drop_index('ix_agents_platform', table_name='agents')
    op.drop_column('agents', 'owner_id')
    op.drop_column('agents', 'agent_metadata')
    op.drop_column('agents', 'endpoint_url')
    op.drop_column('agents', 'platform')
    op.drop_index('ix_agent_reputations_trust_score', table_name='agent_reputations')
    op.drop_index('ix_agent_reputations_success_rate', table_name='agent_reputations')
    op.drop_index('ix_agent_reputations_agent', table_name='agent_reputations')
    op.drop_table('agent_reputations')
    op.drop_index('ix_agent_executions_user', table_name='agent_executions')
    op.drop_index('ix_agent_executions_status', table_name='agent_executions')
    op.drop_index('ix_agent_executions_created', table_name='agent_executions')
    op.drop_index('ix_agent_executions_agent', table_name='agent_executions')
    op.drop_table('agent_executions')
    # ### end Alembic commands ###
